server:
  port: 8762

spring:
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    hostname: eurekaserver2
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka
    register-with-eureka: false
    fetch-registry: false

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)