server:
  port: 8086
spring:
  application:
    name: OrderQueryService
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      import-check:
        enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderQueryDB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,
        http://localhost:8762/eureka/
sleuth:
  sampler:
    probability: 1 #100% (default = 10%)
