spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
      - id: CustomerService
        uri: lb://CustomerService
        predicates:
        - Path=/customers/**
      - id: ProductService
        uri: lb://ProductService
        predicates:
        - Path=/products/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,
                   http://localhost:8762/eureka/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)


